### ISSUE TITLE
Question about developer's environment

### ISSUE THREAD

**Issue by incorpusyehtee** [SirCmpwn/sr.ht#10]
````
proj@proj:~/sr.ht$ python app.py
/home/proj/.local/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from srht.app import app
  File "/home/proj/sr.ht/srht/app.py", line 16, in <module>
    from srht.blueprints.html import html
ImportError: No module named blueprints.html
````

I do not use python much for relatively complex projects like this, but I do not think I have had an environment where importing relative modules works in the way this project seems to require it. Is there any way I can configure my environment to match yours best? Thanks much!

**Comment by SirCmpwn** [comment]
Use python 3.
